# Generated by Django 4.1.2 on 2022-10-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavehistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='leavehistory',
            name='leaveID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
