# Generated by Django 4.1.2 on 2022-10-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0002_remove_leavehistory_id_alter_leavehistory_leaveid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavehistory',
            name='leaveID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
