# Generated by Django 4.1.2 on 2022-10-30 23:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0003_alter_leavehistory_leaveid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavehistory',
            name='request_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('workerID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('managerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveApp.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='leavehistory',
            name='managerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FK2', to='leaveApp.employee'),
        ),
        migrations.AlterField(
            model_name='leavehistory',
            name='workerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FK1', to='leaveApp.employee'),
        ),
    ]
